// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/circuit_breaker component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("circuit_breaker")
	ScopeName = "github.com/sergeysedoy97/opentelemetry-collector-contrib/extension/circuitbreakerextension"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
