// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					IpvsDestinationConnectionActiveCount: IpvsDestinationConnectionActiveCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationConnectionActiveCountMetricAttributeKey{IpvsDestinationConnectionActiveCountMetricAttributeKeyNetmask, IpvsDestinationConnectionActiveCountMetricAttributeKeyProtocol, IpvsDestinationConnectionActiveCountMetricAttributeKeySched, IpvsDestinationConnectionActiveCountMetricAttributeKeyVipAddress, IpvsDestinationConnectionActiveCountMetricAttributeKeyVipFamily, IpvsDestinationConnectionActiveCountMetricAttributeKeyVipPort, IpvsDestinationConnectionActiveCountMetricAttributeKeyForwardType, IpvsDestinationConnectionActiveCountMetricAttributeKeyTunnelPort, IpvsDestinationConnectionActiveCountMetricAttributeKeyTunnelType, IpvsDestinationConnectionActiveCountMetricAttributeKeyRipAddress, IpvsDestinationConnectionActiveCountMetricAttributeKeyRipFamily, IpvsDestinationConnectionActiveCountMetricAttributeKeyRipPort},
					},
					IpvsDestinationConnectionInactiveCount: IpvsDestinationConnectionInactiveCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationConnectionInactiveCountMetricAttributeKey{IpvsDestinationConnectionInactiveCountMetricAttributeKeyNetmask, IpvsDestinationConnectionInactiveCountMetricAttributeKeyProtocol, IpvsDestinationConnectionInactiveCountMetricAttributeKeySched, IpvsDestinationConnectionInactiveCountMetricAttributeKeyVipAddress, IpvsDestinationConnectionInactiveCountMetricAttributeKeyVipFamily, IpvsDestinationConnectionInactiveCountMetricAttributeKeyVipPort, IpvsDestinationConnectionInactiveCountMetricAttributeKeyForwardType, IpvsDestinationConnectionInactiveCountMetricAttributeKeyTunnelPort, IpvsDestinationConnectionInactiveCountMetricAttributeKeyTunnelType, IpvsDestinationConnectionInactiveCountMetricAttributeKeyRipAddress, IpvsDestinationConnectionInactiveCountMetricAttributeKeyRipFamily, IpvsDestinationConnectionInactiveCountMetricAttributeKeyRipPort},
					},
					IpvsDestinationConnectionPersistentCount: IpvsDestinationConnectionPersistentCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationConnectionPersistentCountMetricAttributeKey{IpvsDestinationConnectionPersistentCountMetricAttributeKeyNetmask, IpvsDestinationConnectionPersistentCountMetricAttributeKeyProtocol, IpvsDestinationConnectionPersistentCountMetricAttributeKeySched, IpvsDestinationConnectionPersistentCountMetricAttributeKeyVipAddress, IpvsDestinationConnectionPersistentCountMetricAttributeKeyVipFamily, IpvsDestinationConnectionPersistentCountMetricAttributeKeyVipPort, IpvsDestinationConnectionPersistentCountMetricAttributeKeyForwardType, IpvsDestinationConnectionPersistentCountMetricAttributeKeyTunnelPort, IpvsDestinationConnectionPersistentCountMetricAttributeKeyTunnelType, IpvsDestinationConnectionPersistentCountMetricAttributeKeyRipAddress, IpvsDestinationConnectionPersistentCountMetricAttributeKeyRipFamily, IpvsDestinationConnectionPersistentCountMetricAttributeKeyRipPort},
					},
					IpvsDestinationConnectionRate: IpvsDestinationConnectionRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationConnectionRateMetricAttributeKey{IpvsDestinationConnectionRateMetricAttributeKeyNetmask, IpvsDestinationConnectionRateMetricAttributeKeyProtocol, IpvsDestinationConnectionRateMetricAttributeKeySched, IpvsDestinationConnectionRateMetricAttributeKeyVipAddress, IpvsDestinationConnectionRateMetricAttributeKeyVipFamily, IpvsDestinationConnectionRateMetricAttributeKeyVipPort, IpvsDestinationConnectionRateMetricAttributeKeyForwardType, IpvsDestinationConnectionRateMetricAttributeKeyTunnelPort, IpvsDestinationConnectionRateMetricAttributeKeyTunnelType, IpvsDestinationConnectionRateMetricAttributeKeyRipAddress, IpvsDestinationConnectionRateMetricAttributeKeyRipFamily, IpvsDestinationConnectionRateMetricAttributeKeyRipPort},
					},
					IpvsDestinationConnectionTotal: IpvsDestinationConnectionTotalMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsDestinationConnectionTotalMetricAttributeKey{IpvsDestinationConnectionTotalMetricAttributeKeyNetmask, IpvsDestinationConnectionTotalMetricAttributeKeyProtocol, IpvsDestinationConnectionTotalMetricAttributeKeySched, IpvsDestinationConnectionTotalMetricAttributeKeyVipAddress, IpvsDestinationConnectionTotalMetricAttributeKeyVipFamily, IpvsDestinationConnectionTotalMetricAttributeKeyVipPort, IpvsDestinationConnectionTotalMetricAttributeKeyForwardType, IpvsDestinationConnectionTotalMetricAttributeKeyTunnelPort, IpvsDestinationConnectionTotalMetricAttributeKeyTunnelType, IpvsDestinationConnectionTotalMetricAttributeKeyRipAddress, IpvsDestinationConnectionTotalMetricAttributeKeyRipFamily, IpvsDestinationConnectionTotalMetricAttributeKeyRipPort},
					},
					IpvsDestinationConnectionWeight: IpvsDestinationConnectionWeightMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationConnectionWeightMetricAttributeKey{IpvsDestinationConnectionWeightMetricAttributeKeyNetmask, IpvsDestinationConnectionWeightMetricAttributeKeyProtocol, IpvsDestinationConnectionWeightMetricAttributeKeySched, IpvsDestinationConnectionWeightMetricAttributeKeyVipAddress, IpvsDestinationConnectionWeightMetricAttributeKeyVipFamily, IpvsDestinationConnectionWeightMetricAttributeKeyVipPort, IpvsDestinationConnectionWeightMetricAttributeKeyForwardType, IpvsDestinationConnectionWeightMetricAttributeKeyTunnelPort, IpvsDestinationConnectionWeightMetricAttributeKeyTunnelType, IpvsDestinationConnectionWeightMetricAttributeKeyRipAddress, IpvsDestinationConnectionWeightMetricAttributeKeyRipFamily, IpvsDestinationConnectionWeightMetricAttributeKeyRipPort},
					},
					IpvsDestinationInRate: IpvsDestinationInRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationInRateMetricAttributeKey{IpvsDestinationInRateMetricAttributeKeyNetmask, IpvsDestinationInRateMetricAttributeKeyProtocol, IpvsDestinationInRateMetricAttributeKeySched, IpvsDestinationInRateMetricAttributeKeyVipAddress, IpvsDestinationInRateMetricAttributeKeyVipFamily, IpvsDestinationInRateMetricAttributeKeyVipPort, IpvsDestinationInRateMetricAttributeKeyForwardType, IpvsDestinationInRateMetricAttributeKeyTunnelPort, IpvsDestinationInRateMetricAttributeKeyTunnelType, IpvsDestinationInRateMetricAttributeKeyRipAddress, IpvsDestinationInRateMetricAttributeKeyRipFamily, IpvsDestinationInRateMetricAttributeKeyRipPort},
					},
					IpvsDestinationInTotal: IpvsDestinationInTotalMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsDestinationInTotalMetricAttributeKey{IpvsDestinationInTotalMetricAttributeKeyNetmask, IpvsDestinationInTotalMetricAttributeKeyProtocol, IpvsDestinationInTotalMetricAttributeKeySched, IpvsDestinationInTotalMetricAttributeKeyVipAddress, IpvsDestinationInTotalMetricAttributeKeyVipFamily, IpvsDestinationInTotalMetricAttributeKeyVipPort, IpvsDestinationInTotalMetricAttributeKeyForwardType, IpvsDestinationInTotalMetricAttributeKeyTunnelPort, IpvsDestinationInTotalMetricAttributeKeyTunnelType, IpvsDestinationInTotalMetricAttributeKeyRipAddress, IpvsDestinationInTotalMetricAttributeKeyRipFamily, IpvsDestinationInTotalMetricAttributeKeyRipPort},
					},
					IpvsDestinationOutRate: IpvsDestinationOutRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationOutRateMetricAttributeKey{IpvsDestinationOutRateMetricAttributeKeyNetmask, IpvsDestinationOutRateMetricAttributeKeyProtocol, IpvsDestinationOutRateMetricAttributeKeySched, IpvsDestinationOutRateMetricAttributeKeyVipAddress, IpvsDestinationOutRateMetricAttributeKeyVipFamily, IpvsDestinationOutRateMetricAttributeKeyVipPort, IpvsDestinationOutRateMetricAttributeKeyForwardType, IpvsDestinationOutRateMetricAttributeKeyTunnelPort, IpvsDestinationOutRateMetricAttributeKeyTunnelType, IpvsDestinationOutRateMetricAttributeKeyRipAddress, IpvsDestinationOutRateMetricAttributeKeyRipFamily, IpvsDestinationOutRateMetricAttributeKeyRipPort},
					},
					IpvsDestinationOutTotal: IpvsDestinationOutTotalMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsDestinationOutTotalMetricAttributeKey{IpvsDestinationOutTotalMetricAttributeKeyNetmask, IpvsDestinationOutTotalMetricAttributeKeyProtocol, IpvsDestinationOutTotalMetricAttributeKeySched, IpvsDestinationOutTotalMetricAttributeKeyVipAddress, IpvsDestinationOutTotalMetricAttributeKeyVipFamily, IpvsDestinationOutTotalMetricAttributeKeyVipPort, IpvsDestinationOutTotalMetricAttributeKeyForwardType, IpvsDestinationOutTotalMetricAttributeKeyTunnelPort, IpvsDestinationOutTotalMetricAttributeKeyTunnelType, IpvsDestinationOutTotalMetricAttributeKeyRipAddress, IpvsDestinationOutTotalMetricAttributeKeyRipFamily, IpvsDestinationOutTotalMetricAttributeKeyRipPort},
					},
					IpvsDestinationPacketInRate: IpvsDestinationPacketInRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationPacketInRateMetricAttributeKey{IpvsDestinationPacketInRateMetricAttributeKeyNetmask, IpvsDestinationPacketInRateMetricAttributeKeyProtocol, IpvsDestinationPacketInRateMetricAttributeKeySched, IpvsDestinationPacketInRateMetricAttributeKeyVipAddress, IpvsDestinationPacketInRateMetricAttributeKeyVipFamily, IpvsDestinationPacketInRateMetricAttributeKeyVipPort, IpvsDestinationPacketInRateMetricAttributeKeyForwardType, IpvsDestinationPacketInRateMetricAttributeKeyTunnelPort, IpvsDestinationPacketInRateMetricAttributeKeyTunnelType, IpvsDestinationPacketInRateMetricAttributeKeyRipAddress, IpvsDestinationPacketInRateMetricAttributeKeyRipFamily, IpvsDestinationPacketInRateMetricAttributeKeyRipPort},
					},
					IpvsDestinationPacketInTotal: IpvsDestinationPacketInTotalMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsDestinationPacketInTotalMetricAttributeKey{IpvsDestinationPacketInTotalMetricAttributeKeyNetmask, IpvsDestinationPacketInTotalMetricAttributeKeyProtocol, IpvsDestinationPacketInTotalMetricAttributeKeySched, IpvsDestinationPacketInTotalMetricAttributeKeyVipAddress, IpvsDestinationPacketInTotalMetricAttributeKeyVipFamily, IpvsDestinationPacketInTotalMetricAttributeKeyVipPort, IpvsDestinationPacketInTotalMetricAttributeKeyForwardType, IpvsDestinationPacketInTotalMetricAttributeKeyTunnelPort, IpvsDestinationPacketInTotalMetricAttributeKeyTunnelType, IpvsDestinationPacketInTotalMetricAttributeKeyRipAddress, IpvsDestinationPacketInTotalMetricAttributeKeyRipFamily, IpvsDestinationPacketInTotalMetricAttributeKeyRipPort},
					},
					IpvsDestinationPacketOutRate: IpvsDestinationPacketOutRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationPacketOutRateMetricAttributeKey{IpvsDestinationPacketOutRateMetricAttributeKeyNetmask, IpvsDestinationPacketOutRateMetricAttributeKeyProtocol, IpvsDestinationPacketOutRateMetricAttributeKeySched, IpvsDestinationPacketOutRateMetricAttributeKeyVipAddress, IpvsDestinationPacketOutRateMetricAttributeKeyVipFamily, IpvsDestinationPacketOutRateMetricAttributeKeyVipPort, IpvsDestinationPacketOutRateMetricAttributeKeyForwardType, IpvsDestinationPacketOutRateMetricAttributeKeyTunnelPort, IpvsDestinationPacketOutRateMetricAttributeKeyTunnelType, IpvsDestinationPacketOutRateMetricAttributeKeyRipAddress, IpvsDestinationPacketOutRateMetricAttributeKeyRipFamily, IpvsDestinationPacketOutRateMetricAttributeKeyRipPort},
					},
					IpvsDestinationPacketOutTotal: IpvsDestinationPacketOutTotalMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsDestinationPacketOutTotalMetricAttributeKey{IpvsDestinationPacketOutTotalMetricAttributeKeyNetmask, IpvsDestinationPacketOutTotalMetricAttributeKeyProtocol, IpvsDestinationPacketOutTotalMetricAttributeKeySched, IpvsDestinationPacketOutTotalMetricAttributeKeyVipAddress, IpvsDestinationPacketOutTotalMetricAttributeKeyVipFamily, IpvsDestinationPacketOutTotalMetricAttributeKeyVipPort, IpvsDestinationPacketOutTotalMetricAttributeKeyForwardType, IpvsDestinationPacketOutTotalMetricAttributeKeyTunnelPort, IpvsDestinationPacketOutTotalMetricAttributeKeyTunnelType, IpvsDestinationPacketOutTotalMetricAttributeKeyRipAddress, IpvsDestinationPacketOutTotalMetricAttributeKeyRipFamily, IpvsDestinationPacketOutTotalMetricAttributeKeyRipPort},
					},
					IpvsServiceConnectionRate: IpvsServiceConnectionRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsServiceConnectionRateMetricAttributeKey{IpvsServiceConnectionRateMetricAttributeKeyNetmask, IpvsServiceConnectionRateMetricAttributeKeyProtocol, IpvsServiceConnectionRateMetricAttributeKeySched, IpvsServiceConnectionRateMetricAttributeKeyVipAddress, IpvsServiceConnectionRateMetricAttributeKeyVipFamily, IpvsServiceConnectionRateMetricAttributeKeyVipPort},
					},
					IpvsServiceConnectionTotal: IpvsServiceConnectionTotalMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsServiceConnectionTotalMetricAttributeKey{IpvsServiceConnectionTotalMetricAttributeKeyNetmask, IpvsServiceConnectionTotalMetricAttributeKeyProtocol, IpvsServiceConnectionTotalMetricAttributeKeySched, IpvsServiceConnectionTotalMetricAttributeKeyVipAddress, IpvsServiceConnectionTotalMetricAttributeKeyVipFamily, IpvsServiceConnectionTotalMetricAttributeKeyVipPort},
					},
					IpvsServiceInRate: IpvsServiceInRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsServiceInRateMetricAttributeKey{IpvsServiceInRateMetricAttributeKeyNetmask, IpvsServiceInRateMetricAttributeKeyProtocol, IpvsServiceInRateMetricAttributeKeySched, IpvsServiceInRateMetricAttributeKeyVipAddress, IpvsServiceInRateMetricAttributeKeyVipFamily, IpvsServiceInRateMetricAttributeKeyVipPort},
					},
					IpvsServiceInTotal: IpvsServiceInTotalMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsServiceInTotalMetricAttributeKey{IpvsServiceInTotalMetricAttributeKeyNetmask, IpvsServiceInTotalMetricAttributeKeyProtocol, IpvsServiceInTotalMetricAttributeKeySched, IpvsServiceInTotalMetricAttributeKeyVipAddress, IpvsServiceInTotalMetricAttributeKeyVipFamily, IpvsServiceInTotalMetricAttributeKeyVipPort},
					},
					IpvsServiceOutRate: IpvsServiceOutRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsServiceOutRateMetricAttributeKey{IpvsServiceOutRateMetricAttributeKeyNetmask, IpvsServiceOutRateMetricAttributeKeyProtocol, IpvsServiceOutRateMetricAttributeKeySched, IpvsServiceOutRateMetricAttributeKeyVipAddress, IpvsServiceOutRateMetricAttributeKeyVipFamily, IpvsServiceOutRateMetricAttributeKeyVipPort},
					},
					IpvsServiceOutTotal: IpvsServiceOutTotalMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsServiceOutTotalMetricAttributeKey{IpvsServiceOutTotalMetricAttributeKeyNetmask, IpvsServiceOutTotalMetricAttributeKeyProtocol, IpvsServiceOutTotalMetricAttributeKeySched, IpvsServiceOutTotalMetricAttributeKeyVipAddress, IpvsServiceOutTotalMetricAttributeKeyVipFamily, IpvsServiceOutTotalMetricAttributeKeyVipPort},
					},
					IpvsServicePacketInRate: IpvsServicePacketInRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsServicePacketInRateMetricAttributeKey{IpvsServicePacketInRateMetricAttributeKeyNetmask, IpvsServicePacketInRateMetricAttributeKeyProtocol, IpvsServicePacketInRateMetricAttributeKeySched, IpvsServicePacketInRateMetricAttributeKeyVipAddress, IpvsServicePacketInRateMetricAttributeKeyVipFamily, IpvsServicePacketInRateMetricAttributeKeyVipPort},
					},
					IpvsServicePacketInTotal: IpvsServicePacketInTotalMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsServicePacketInTotalMetricAttributeKey{IpvsServicePacketInTotalMetricAttributeKeyNetmask, IpvsServicePacketInTotalMetricAttributeKeyProtocol, IpvsServicePacketInTotalMetricAttributeKeySched, IpvsServicePacketInTotalMetricAttributeKeyVipAddress, IpvsServicePacketInTotalMetricAttributeKeyVipFamily, IpvsServicePacketInTotalMetricAttributeKeyVipPort},
					},
					IpvsServicePacketOutRate: IpvsServicePacketOutRateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsServicePacketOutRateMetricAttributeKey{IpvsServicePacketOutRateMetricAttributeKeyNetmask, IpvsServicePacketOutRateMetricAttributeKeyProtocol, IpvsServicePacketOutRateMetricAttributeKeySched, IpvsServicePacketOutRateMetricAttributeKeyVipAddress, IpvsServicePacketOutRateMetricAttributeKeyVipFamily, IpvsServicePacketOutRateMetricAttributeKeyVipPort},
					},
					IpvsServicePacketOutTotal: IpvsServicePacketOutTotalMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsServicePacketOutTotalMetricAttributeKey{IpvsServicePacketOutTotalMetricAttributeKeyNetmask, IpvsServicePacketOutTotalMetricAttributeKeyProtocol, IpvsServicePacketOutTotalMetricAttributeKeySched, IpvsServicePacketOutTotalMetricAttributeKeyVipAddress, IpvsServicePacketOutTotalMetricAttributeKeyVipFamily, IpvsServicePacketOutTotalMetricAttributeKeyVipPort},
					},
					IpvsServiceTimeout: IpvsServiceTimeoutMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsServiceTimeoutMetricAttributeKey{IpvsServiceTimeoutMetricAttributeKeyNetmask, IpvsServiceTimeoutMetricAttributeKeyProtocol, IpvsServiceTimeoutMetricAttributeKeySched, IpvsServiceTimeoutMetricAttributeKeyVipAddress, IpvsServiceTimeoutMetricAttributeKeyVipFamily, IpvsServiceTimeoutMetricAttributeKeyVipPort},
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					IpvsDestinationConnectionActiveCount: IpvsDestinationConnectionActiveCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationConnectionActiveCountMetricAttributeKey{IpvsDestinationConnectionActiveCountMetricAttributeKeyNetmask, IpvsDestinationConnectionActiveCountMetricAttributeKeyProtocol, IpvsDestinationConnectionActiveCountMetricAttributeKeySched, IpvsDestinationConnectionActiveCountMetricAttributeKeyVipAddress, IpvsDestinationConnectionActiveCountMetricAttributeKeyVipFamily, IpvsDestinationConnectionActiveCountMetricAttributeKeyVipPort, IpvsDestinationConnectionActiveCountMetricAttributeKeyForwardType, IpvsDestinationConnectionActiveCountMetricAttributeKeyTunnelPort, IpvsDestinationConnectionActiveCountMetricAttributeKeyTunnelType, IpvsDestinationConnectionActiveCountMetricAttributeKeyRipAddress, IpvsDestinationConnectionActiveCountMetricAttributeKeyRipFamily, IpvsDestinationConnectionActiveCountMetricAttributeKeyRipPort},
					},
					IpvsDestinationConnectionInactiveCount: IpvsDestinationConnectionInactiveCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationConnectionInactiveCountMetricAttributeKey{IpvsDestinationConnectionInactiveCountMetricAttributeKeyNetmask, IpvsDestinationConnectionInactiveCountMetricAttributeKeyProtocol, IpvsDestinationConnectionInactiveCountMetricAttributeKeySched, IpvsDestinationConnectionInactiveCountMetricAttributeKeyVipAddress, IpvsDestinationConnectionInactiveCountMetricAttributeKeyVipFamily, IpvsDestinationConnectionInactiveCountMetricAttributeKeyVipPort, IpvsDestinationConnectionInactiveCountMetricAttributeKeyForwardType, IpvsDestinationConnectionInactiveCountMetricAttributeKeyTunnelPort, IpvsDestinationConnectionInactiveCountMetricAttributeKeyTunnelType, IpvsDestinationConnectionInactiveCountMetricAttributeKeyRipAddress, IpvsDestinationConnectionInactiveCountMetricAttributeKeyRipFamily, IpvsDestinationConnectionInactiveCountMetricAttributeKeyRipPort},
					},
					IpvsDestinationConnectionPersistentCount: IpvsDestinationConnectionPersistentCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationConnectionPersistentCountMetricAttributeKey{IpvsDestinationConnectionPersistentCountMetricAttributeKeyNetmask, IpvsDestinationConnectionPersistentCountMetricAttributeKeyProtocol, IpvsDestinationConnectionPersistentCountMetricAttributeKeySched, IpvsDestinationConnectionPersistentCountMetricAttributeKeyVipAddress, IpvsDestinationConnectionPersistentCountMetricAttributeKeyVipFamily, IpvsDestinationConnectionPersistentCountMetricAttributeKeyVipPort, IpvsDestinationConnectionPersistentCountMetricAttributeKeyForwardType, IpvsDestinationConnectionPersistentCountMetricAttributeKeyTunnelPort, IpvsDestinationConnectionPersistentCountMetricAttributeKeyTunnelType, IpvsDestinationConnectionPersistentCountMetricAttributeKeyRipAddress, IpvsDestinationConnectionPersistentCountMetricAttributeKeyRipFamily, IpvsDestinationConnectionPersistentCountMetricAttributeKeyRipPort},
					},
					IpvsDestinationConnectionRate: IpvsDestinationConnectionRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationConnectionRateMetricAttributeKey{IpvsDestinationConnectionRateMetricAttributeKeyNetmask, IpvsDestinationConnectionRateMetricAttributeKeyProtocol, IpvsDestinationConnectionRateMetricAttributeKeySched, IpvsDestinationConnectionRateMetricAttributeKeyVipAddress, IpvsDestinationConnectionRateMetricAttributeKeyVipFamily, IpvsDestinationConnectionRateMetricAttributeKeyVipPort, IpvsDestinationConnectionRateMetricAttributeKeyForwardType, IpvsDestinationConnectionRateMetricAttributeKeyTunnelPort, IpvsDestinationConnectionRateMetricAttributeKeyTunnelType, IpvsDestinationConnectionRateMetricAttributeKeyRipAddress, IpvsDestinationConnectionRateMetricAttributeKeyRipFamily, IpvsDestinationConnectionRateMetricAttributeKeyRipPort},
					},
					IpvsDestinationConnectionTotal: IpvsDestinationConnectionTotalMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsDestinationConnectionTotalMetricAttributeKey{IpvsDestinationConnectionTotalMetricAttributeKeyNetmask, IpvsDestinationConnectionTotalMetricAttributeKeyProtocol, IpvsDestinationConnectionTotalMetricAttributeKeySched, IpvsDestinationConnectionTotalMetricAttributeKeyVipAddress, IpvsDestinationConnectionTotalMetricAttributeKeyVipFamily, IpvsDestinationConnectionTotalMetricAttributeKeyVipPort, IpvsDestinationConnectionTotalMetricAttributeKeyForwardType, IpvsDestinationConnectionTotalMetricAttributeKeyTunnelPort, IpvsDestinationConnectionTotalMetricAttributeKeyTunnelType, IpvsDestinationConnectionTotalMetricAttributeKeyRipAddress, IpvsDestinationConnectionTotalMetricAttributeKeyRipFamily, IpvsDestinationConnectionTotalMetricAttributeKeyRipPort},
					},
					IpvsDestinationConnectionWeight: IpvsDestinationConnectionWeightMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationConnectionWeightMetricAttributeKey{IpvsDestinationConnectionWeightMetricAttributeKeyNetmask, IpvsDestinationConnectionWeightMetricAttributeKeyProtocol, IpvsDestinationConnectionWeightMetricAttributeKeySched, IpvsDestinationConnectionWeightMetricAttributeKeyVipAddress, IpvsDestinationConnectionWeightMetricAttributeKeyVipFamily, IpvsDestinationConnectionWeightMetricAttributeKeyVipPort, IpvsDestinationConnectionWeightMetricAttributeKeyForwardType, IpvsDestinationConnectionWeightMetricAttributeKeyTunnelPort, IpvsDestinationConnectionWeightMetricAttributeKeyTunnelType, IpvsDestinationConnectionWeightMetricAttributeKeyRipAddress, IpvsDestinationConnectionWeightMetricAttributeKeyRipFamily, IpvsDestinationConnectionWeightMetricAttributeKeyRipPort},
					},
					IpvsDestinationInRate: IpvsDestinationInRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationInRateMetricAttributeKey{IpvsDestinationInRateMetricAttributeKeyNetmask, IpvsDestinationInRateMetricAttributeKeyProtocol, IpvsDestinationInRateMetricAttributeKeySched, IpvsDestinationInRateMetricAttributeKeyVipAddress, IpvsDestinationInRateMetricAttributeKeyVipFamily, IpvsDestinationInRateMetricAttributeKeyVipPort, IpvsDestinationInRateMetricAttributeKeyForwardType, IpvsDestinationInRateMetricAttributeKeyTunnelPort, IpvsDestinationInRateMetricAttributeKeyTunnelType, IpvsDestinationInRateMetricAttributeKeyRipAddress, IpvsDestinationInRateMetricAttributeKeyRipFamily, IpvsDestinationInRateMetricAttributeKeyRipPort},
					},
					IpvsDestinationInTotal: IpvsDestinationInTotalMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsDestinationInTotalMetricAttributeKey{IpvsDestinationInTotalMetricAttributeKeyNetmask, IpvsDestinationInTotalMetricAttributeKeyProtocol, IpvsDestinationInTotalMetricAttributeKeySched, IpvsDestinationInTotalMetricAttributeKeyVipAddress, IpvsDestinationInTotalMetricAttributeKeyVipFamily, IpvsDestinationInTotalMetricAttributeKeyVipPort, IpvsDestinationInTotalMetricAttributeKeyForwardType, IpvsDestinationInTotalMetricAttributeKeyTunnelPort, IpvsDestinationInTotalMetricAttributeKeyTunnelType, IpvsDestinationInTotalMetricAttributeKeyRipAddress, IpvsDestinationInTotalMetricAttributeKeyRipFamily, IpvsDestinationInTotalMetricAttributeKeyRipPort},
					},
					IpvsDestinationOutRate: IpvsDestinationOutRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationOutRateMetricAttributeKey{IpvsDestinationOutRateMetricAttributeKeyNetmask, IpvsDestinationOutRateMetricAttributeKeyProtocol, IpvsDestinationOutRateMetricAttributeKeySched, IpvsDestinationOutRateMetricAttributeKeyVipAddress, IpvsDestinationOutRateMetricAttributeKeyVipFamily, IpvsDestinationOutRateMetricAttributeKeyVipPort, IpvsDestinationOutRateMetricAttributeKeyForwardType, IpvsDestinationOutRateMetricAttributeKeyTunnelPort, IpvsDestinationOutRateMetricAttributeKeyTunnelType, IpvsDestinationOutRateMetricAttributeKeyRipAddress, IpvsDestinationOutRateMetricAttributeKeyRipFamily, IpvsDestinationOutRateMetricAttributeKeyRipPort},
					},
					IpvsDestinationOutTotal: IpvsDestinationOutTotalMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsDestinationOutTotalMetricAttributeKey{IpvsDestinationOutTotalMetricAttributeKeyNetmask, IpvsDestinationOutTotalMetricAttributeKeyProtocol, IpvsDestinationOutTotalMetricAttributeKeySched, IpvsDestinationOutTotalMetricAttributeKeyVipAddress, IpvsDestinationOutTotalMetricAttributeKeyVipFamily, IpvsDestinationOutTotalMetricAttributeKeyVipPort, IpvsDestinationOutTotalMetricAttributeKeyForwardType, IpvsDestinationOutTotalMetricAttributeKeyTunnelPort, IpvsDestinationOutTotalMetricAttributeKeyTunnelType, IpvsDestinationOutTotalMetricAttributeKeyRipAddress, IpvsDestinationOutTotalMetricAttributeKeyRipFamily, IpvsDestinationOutTotalMetricAttributeKeyRipPort},
					},
					IpvsDestinationPacketInRate: IpvsDestinationPacketInRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationPacketInRateMetricAttributeKey{IpvsDestinationPacketInRateMetricAttributeKeyNetmask, IpvsDestinationPacketInRateMetricAttributeKeyProtocol, IpvsDestinationPacketInRateMetricAttributeKeySched, IpvsDestinationPacketInRateMetricAttributeKeyVipAddress, IpvsDestinationPacketInRateMetricAttributeKeyVipFamily, IpvsDestinationPacketInRateMetricAttributeKeyVipPort, IpvsDestinationPacketInRateMetricAttributeKeyForwardType, IpvsDestinationPacketInRateMetricAttributeKeyTunnelPort, IpvsDestinationPacketInRateMetricAttributeKeyTunnelType, IpvsDestinationPacketInRateMetricAttributeKeyRipAddress, IpvsDestinationPacketInRateMetricAttributeKeyRipFamily, IpvsDestinationPacketInRateMetricAttributeKeyRipPort},
					},
					IpvsDestinationPacketInTotal: IpvsDestinationPacketInTotalMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsDestinationPacketInTotalMetricAttributeKey{IpvsDestinationPacketInTotalMetricAttributeKeyNetmask, IpvsDestinationPacketInTotalMetricAttributeKeyProtocol, IpvsDestinationPacketInTotalMetricAttributeKeySched, IpvsDestinationPacketInTotalMetricAttributeKeyVipAddress, IpvsDestinationPacketInTotalMetricAttributeKeyVipFamily, IpvsDestinationPacketInTotalMetricAttributeKeyVipPort, IpvsDestinationPacketInTotalMetricAttributeKeyForwardType, IpvsDestinationPacketInTotalMetricAttributeKeyTunnelPort, IpvsDestinationPacketInTotalMetricAttributeKeyTunnelType, IpvsDestinationPacketInTotalMetricAttributeKeyRipAddress, IpvsDestinationPacketInTotalMetricAttributeKeyRipFamily, IpvsDestinationPacketInTotalMetricAttributeKeyRipPort},
					},
					IpvsDestinationPacketOutRate: IpvsDestinationPacketOutRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsDestinationPacketOutRateMetricAttributeKey{IpvsDestinationPacketOutRateMetricAttributeKeyNetmask, IpvsDestinationPacketOutRateMetricAttributeKeyProtocol, IpvsDestinationPacketOutRateMetricAttributeKeySched, IpvsDestinationPacketOutRateMetricAttributeKeyVipAddress, IpvsDestinationPacketOutRateMetricAttributeKeyVipFamily, IpvsDestinationPacketOutRateMetricAttributeKeyVipPort, IpvsDestinationPacketOutRateMetricAttributeKeyForwardType, IpvsDestinationPacketOutRateMetricAttributeKeyTunnelPort, IpvsDestinationPacketOutRateMetricAttributeKeyTunnelType, IpvsDestinationPacketOutRateMetricAttributeKeyRipAddress, IpvsDestinationPacketOutRateMetricAttributeKeyRipFamily, IpvsDestinationPacketOutRateMetricAttributeKeyRipPort},
					},
					IpvsDestinationPacketOutTotal: IpvsDestinationPacketOutTotalMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsDestinationPacketOutTotalMetricAttributeKey{IpvsDestinationPacketOutTotalMetricAttributeKeyNetmask, IpvsDestinationPacketOutTotalMetricAttributeKeyProtocol, IpvsDestinationPacketOutTotalMetricAttributeKeySched, IpvsDestinationPacketOutTotalMetricAttributeKeyVipAddress, IpvsDestinationPacketOutTotalMetricAttributeKeyVipFamily, IpvsDestinationPacketOutTotalMetricAttributeKeyVipPort, IpvsDestinationPacketOutTotalMetricAttributeKeyForwardType, IpvsDestinationPacketOutTotalMetricAttributeKeyTunnelPort, IpvsDestinationPacketOutTotalMetricAttributeKeyTunnelType, IpvsDestinationPacketOutTotalMetricAttributeKeyRipAddress, IpvsDestinationPacketOutTotalMetricAttributeKeyRipFamily, IpvsDestinationPacketOutTotalMetricAttributeKeyRipPort},
					},
					IpvsServiceConnectionRate: IpvsServiceConnectionRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsServiceConnectionRateMetricAttributeKey{IpvsServiceConnectionRateMetricAttributeKeyNetmask, IpvsServiceConnectionRateMetricAttributeKeyProtocol, IpvsServiceConnectionRateMetricAttributeKeySched, IpvsServiceConnectionRateMetricAttributeKeyVipAddress, IpvsServiceConnectionRateMetricAttributeKeyVipFamily, IpvsServiceConnectionRateMetricAttributeKeyVipPort},
					},
					IpvsServiceConnectionTotal: IpvsServiceConnectionTotalMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsServiceConnectionTotalMetricAttributeKey{IpvsServiceConnectionTotalMetricAttributeKeyNetmask, IpvsServiceConnectionTotalMetricAttributeKeyProtocol, IpvsServiceConnectionTotalMetricAttributeKeySched, IpvsServiceConnectionTotalMetricAttributeKeyVipAddress, IpvsServiceConnectionTotalMetricAttributeKeyVipFamily, IpvsServiceConnectionTotalMetricAttributeKeyVipPort},
					},
					IpvsServiceInRate: IpvsServiceInRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsServiceInRateMetricAttributeKey{IpvsServiceInRateMetricAttributeKeyNetmask, IpvsServiceInRateMetricAttributeKeyProtocol, IpvsServiceInRateMetricAttributeKeySched, IpvsServiceInRateMetricAttributeKeyVipAddress, IpvsServiceInRateMetricAttributeKeyVipFamily, IpvsServiceInRateMetricAttributeKeyVipPort},
					},
					IpvsServiceInTotal: IpvsServiceInTotalMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsServiceInTotalMetricAttributeKey{IpvsServiceInTotalMetricAttributeKeyNetmask, IpvsServiceInTotalMetricAttributeKeyProtocol, IpvsServiceInTotalMetricAttributeKeySched, IpvsServiceInTotalMetricAttributeKeyVipAddress, IpvsServiceInTotalMetricAttributeKeyVipFamily, IpvsServiceInTotalMetricAttributeKeyVipPort},
					},
					IpvsServiceOutRate: IpvsServiceOutRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsServiceOutRateMetricAttributeKey{IpvsServiceOutRateMetricAttributeKeyNetmask, IpvsServiceOutRateMetricAttributeKeyProtocol, IpvsServiceOutRateMetricAttributeKeySched, IpvsServiceOutRateMetricAttributeKeyVipAddress, IpvsServiceOutRateMetricAttributeKeyVipFamily, IpvsServiceOutRateMetricAttributeKeyVipPort},
					},
					IpvsServiceOutTotal: IpvsServiceOutTotalMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsServiceOutTotalMetricAttributeKey{IpvsServiceOutTotalMetricAttributeKeyNetmask, IpvsServiceOutTotalMetricAttributeKeyProtocol, IpvsServiceOutTotalMetricAttributeKeySched, IpvsServiceOutTotalMetricAttributeKeyVipAddress, IpvsServiceOutTotalMetricAttributeKeyVipFamily, IpvsServiceOutTotalMetricAttributeKeyVipPort},
					},
					IpvsServicePacketInRate: IpvsServicePacketInRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsServicePacketInRateMetricAttributeKey{IpvsServicePacketInRateMetricAttributeKeyNetmask, IpvsServicePacketInRateMetricAttributeKeyProtocol, IpvsServicePacketInRateMetricAttributeKeySched, IpvsServicePacketInRateMetricAttributeKeyVipAddress, IpvsServicePacketInRateMetricAttributeKeyVipFamily, IpvsServicePacketInRateMetricAttributeKeyVipPort},
					},
					IpvsServicePacketInTotal: IpvsServicePacketInTotalMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsServicePacketInTotalMetricAttributeKey{IpvsServicePacketInTotalMetricAttributeKeyNetmask, IpvsServicePacketInTotalMetricAttributeKeyProtocol, IpvsServicePacketInTotalMetricAttributeKeySched, IpvsServicePacketInTotalMetricAttributeKeyVipAddress, IpvsServicePacketInTotalMetricAttributeKeyVipFamily, IpvsServicePacketInTotalMetricAttributeKeyVipPort},
					},
					IpvsServicePacketOutRate: IpvsServicePacketOutRateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsServicePacketOutRateMetricAttributeKey{IpvsServicePacketOutRateMetricAttributeKeyNetmask, IpvsServicePacketOutRateMetricAttributeKeyProtocol, IpvsServicePacketOutRateMetricAttributeKeySched, IpvsServicePacketOutRateMetricAttributeKeyVipAddress, IpvsServicePacketOutRateMetricAttributeKeyVipFamily, IpvsServicePacketOutRateMetricAttributeKeyVipPort},
					},
					IpvsServicePacketOutTotal: IpvsServicePacketOutTotalMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []IpvsServicePacketOutTotalMetricAttributeKey{IpvsServicePacketOutTotalMetricAttributeKeyNetmask, IpvsServicePacketOutTotalMetricAttributeKeyProtocol, IpvsServicePacketOutTotalMetricAttributeKeySched, IpvsServicePacketOutTotalMetricAttributeKeyVipAddress, IpvsServicePacketOutTotalMetricAttributeKeyVipFamily, IpvsServicePacketOutTotalMetricAttributeKeyVipPort},
					},
					IpvsServiceTimeout: IpvsServiceTimeoutMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []IpvsServiceTimeoutMetricAttributeKey{IpvsServiceTimeoutMetricAttributeKeyNetmask, IpvsServiceTimeoutMetricAttributeKeyProtocol, IpvsServiceTimeoutMetricAttributeKeySched, IpvsServiceTimeoutMetricAttributeKeyVipAddress, IpvsServiceTimeoutMetricAttributeKeyVipFamily, IpvsServiceTimeoutMetricAttributeKeyVipPort},
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(IpvsDestinationConnectionActiveCountMetricConfig{}, IpvsDestinationConnectionInactiveCountMetricConfig{}, IpvsDestinationConnectionPersistentCountMetricConfig{}, IpvsDestinationConnectionRateMetricConfig{}, IpvsDestinationConnectionTotalMetricConfig{}, IpvsDestinationConnectionWeightMetricConfig{}, IpvsDestinationInRateMetricConfig{}, IpvsDestinationInTotalMetricConfig{}, IpvsDestinationOutRateMetricConfig{}, IpvsDestinationOutTotalMetricConfig{}, IpvsDestinationPacketInRateMetricConfig{}, IpvsDestinationPacketInTotalMetricConfig{}, IpvsDestinationPacketOutRateMetricConfig{}, IpvsDestinationPacketOutTotalMetricConfig{}, IpvsServiceConnectionRateMetricConfig{}, IpvsServiceConnectionTotalMetricConfig{}, IpvsServiceInRateMetricConfig{}, IpvsServiceInTotalMetricConfig{}, IpvsServiceOutRateMetricConfig{}, IpvsServiceOutTotalMetricConfig{}, IpvsServicePacketInRateMetricConfig{}, IpvsServicePacketInTotalMetricConfig{}, IpvsServicePacketOutRateMetricConfig{}, IpvsServicePacketOutTotalMetricConfig{}, IpvsServiceTimeoutMetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
