// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/sergeysedoy97/opentelemetry-collector-contrib/exporter/elasticsearchtsdsexporter")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/sergeysedoy97/opentelemetry-collector-contrib/exporter/elasticsearchtsdsexporter")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                            metric.Meter
	mu                               sync.Mutex
	registrations                    []metric.Registration
	ElasticsearchBulkRequestsLatency metric.Float64Histogram
	ElasticsearchDatapointsReceived  metric.Int64Counter
	ElasticsearchDocsProcessed       metric.Int64Counter
	ElasticsearchDocsReceived        metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ElasticsearchBulkRequestsLatency, err = builder.meter.Float64Histogram(
		"otelcol.elasticsearch.bulk_requests.latency",
		metric.WithDescription("none [Alpha]"),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries([]float64{0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5, 2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9}...),
	)
	errs = errors.Join(errs, err)
	builder.ElasticsearchDatapointsReceived, err = builder.meter.Int64Counter(
		"otelcol.elasticsearch.datapoints.received",
		metric.WithDescription("none [Alpha]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ElasticsearchDocsProcessed, err = builder.meter.Int64Counter(
		"otelcol.elasticsearch.docs.processed",
		metric.WithDescription("none [Alpha]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ElasticsearchDocsReceived, err = builder.meter.Int64Counter(
		"otelcol.elasticsearch.docs.received",
		metric.WithDescription("none [Alpha]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
