// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/elasticsearch component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("elasticsearch")
	ScopeName = "github.com/sergeysedoy97/opentelemetry-collector-contrib/processor/elasticsearchprocessor"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
