// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("histogramtogauge")
	ScopeName = "github.com/sergeysedoy97/opentelemetry-collector-contrib/processor/histogramtogaugeprocessor"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
