// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/one_conf component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("one_conf")
	ScopeName = "github.com/sergeysedoy97/opentelemetry-collector-contrib/extension/oneconfextension"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
